name: CI

on:
  push:
    tags:
    - '*'
  schedule:
    - cron:  '0 0 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15'
    - name: Build release file
      run: ./build-release.sh
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/*.tar.gz
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true